### PR TITLE
Added support for lightweight transactions.

### PR DESCRIPTION
**Pull request by kayceesrk**
Added support for Cassandra's [lightweight transactions](http://www.datastax.com/dev/blog/lightweight-transactions-in-cassandra-2-0). In order to do this, I have had to update to [CQL binary protocol v2](https://github.com/apache/cassandra/blob/trunk/doc/native_protocol_v2.spec). A new primitive `executeTrans` has been added.

### CODE REVIEW

**Comment by the-real-blackh** [comment]
I'm quite busy and not working with cassandra at the moment. Do you want me to give you github and hackage access so you can be the maintainer, at least for now?

**Comment by kayceesrk** [comment]
Sure. I'll be happy to. I'm kayceesrk on hackage.

**Comment by the-real-blackh** [comment]
You should have privileges for the cassandra-cql package on hackage and here on GitHub, so please go ahead and release as you like. Better that someone who is using it is maintaining it. Let me know if anything doesn't work.

**Comment by kayceesrk** [comment]
Great. Thanks for your work!

**Pull request merged**
